### PR TITLE
Export FindClass in Env

### LINKED ISSUE #61: Expose FindClass
Hey,
Is there any way to retrieve `java/lang/Class` without having to call `java/lang/Class.forName` (Doesn't work with external libraries)?
Why can't we just export `callFindClass`?

Best regards

### PR DESCRIPTION
**Pull request by Londek**
Closes #61

### CODE REVIEW

**Comment by timob** [comment]
Looks good, would be good to add the documentation comment.

**Comment by timob** [comment]
I think there is a problem with the last commit, on line 102.

**Comment by Londek** [comment]
Sorry for hussle, such a small typo and would break entire code.
I added support for `int32` in `helper.go`. I don't think it deserves its own pull request, it's not complex change at all.
Hopefully now its alright.

**Comment by timob** [comment]
Why do we need to handle int32 in that function since it's internal and we never pass an int32 value to it as first argument in `jnigi.go`? Is there a reason you want these changes?

**Comment by timob** [comment]
I've added https://github.com/timob/jnigi/issues/64. If that looks good, i will do a PR for this. For this PR if you remove the change to helper.go I'll merge.

**Comment by Londek** [comment]
Hey, I didn't have time to reply, it was really busy week for me.
I guess you are right about creating new PR, I'm gonna remove latest commit in few minutes
Thanks ;)

**Comment by timob** [comment]
Great 🎉, thanks!

**Pull request merged**
